---
title: zackpi.github.io
timezone: America/New_York
collections:
  blog:
    title: Blog Posts
    output: true
  hobby:
    title: Hobby Projects
    output: true
  work:
    title: Work Projects
    output: true
  random:
    title: Random Stuff
    output: true

name: Zachary Pitcher
description: zackpi personal website
google_verification: 
include:
- ".htaccess"
exclude:
- README.md
- LICENSE
sass:
  style: compressed
  sass_dir: _sass
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
